### ISSUE TITLE
geolocation denied (preload issue)

### ISSUE THREAD

**Issue by Zaptronic** [bmoren/p5.geolocation#2]
I put the getCurrentPosition() function in the preload function in my sketch. When the user denies geolocation in the browser it never leaves the preload function. The geocheck function will never fire since it won't reach the setup functionality. I also tried the error callback function but it still doesn't leave the preload function. Am I doing something wrong?

**Comment by bmoren** [comment]
I didn't build in a way to handle this, I will look into it. In the mean time, I suggest using getCurrentPosition with a callback : https://github.com/bmoren/p5.geolocation#getcurrentposition-used-with-a-callback

**Comment by Zaptronic** [comment]
Thanks, I will try that.
