### ISSUE TITLE
Seems to be broken with recent p5.js versions

### ISSUE THREAD

**Issue by trych** [bmoren/p5.geolocation#8]
Not sure, what exactly is failing, but I don't get this to work anymore with recent p5.js versions.
Was just about to test a script that I demonstrated in class last year, using p5.js `v0.5.4` and it does not work anymore in `v0.5.16`. Not sure, at which version exactly it broke.

When I use the provided example for `getCurrentPosition()`

```js
var locationData;
function preload(){
    locationData =  getCurrentPosition();
}

function setup() {
    print(locationData.latitude)
    print(locationData.longitude)
    print(locationData.accuracy)
    print(locationData.altitude)
    print(locationData.altitudeAccuracy)
    print(locationData.heading)
    print(locationData.speed)
}
```
it keeps loading forever (displaying the "Loading...", which indicates it is currently stuck in the preload function).

It _does_ display the console output of `p5.geolocation Loaded`, so it loads the library for sure, but it is unable to get the current position.

**Comment by bmoren** [comment]
Can you verify what browser you are using, and that you are serving the sketch via HTTPS?

**Comment by bmoren** [comment]
It could also be that at one point you denied location services to your example and it's silently failing see issue #2

**Comment by kyungyunlee** [comment]
Hi, I am trying to run it in my ios9 device and experiencing the same problem...

Thanks!

**Comment by bmoren** [comment]
This is a bug with the preload system. For the time being – use a callback and things should work. remember that the sketch needs to be served via https! 

```javascript
function setup(){
    getCurrentPosition(doThisOnLocation)
}

function doThisOnLocation(position){
    print("lat: " + position.latitude);
    print("long: " + position.longitude);
}
```

**Comment by kyungyunlee** [comment]
@bmoren  Oh I see, thank you!!

**Comment by mikima** [comment]
With the new version of P5, this library would broke the preload() function.

This means that even if you do nothing with p5.geolocation, if you have instruction in the `preload()` function thee sketch won't work.

Looking to [the documentation](https://github.com/processing/p5.js/blob/master/developer_docs/creating_libraries.md#use-registerpreloadmethod-to-register-names-of-methods-with-p5-that-may-be-called-in-preload), it seems that in the latest P5 version, `prototype.registerPreloadMethod` requires two parameters, see reference.

Changing line 75 in this way, it solves the problem of using any other function in `preload()`:

```
p5.prototype.registerPreloadMethod('getCurrentPosition', p5.prototype);
```

Still, if you use `getCurrentPosition()` in `preload()`, it remains stuck preloading.

It seems that it's not able to evaluate the end of the async code.

I had a look to a [discussion on the topic](https://github.com/processing/p5.js/issues/815) but still is not clear to me what is not working.

Looking to another library ([p5.sound](https://github.com/processing/p5.js-sound/blob/master/lib/p5.sound.js)) it uses a `_decrementPreload()` but it's really unclear its role to me.

**Comment by bmoren** [comment]
Thanks for the investigation, I welcome a pull request to solve this issue. I don't have the capacity to fix the issue at the moment, and If a short term fix is needed, the preload method can be removed from the library by deleting line 75

**Comment by mikima** [comment]
@bmoren fixed, sent a pull request. Let me know if it works for you.
